# Generated by Django 4.1.7 on 2023-03-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.CharField(max_length=2, verbose_name='sigla')),
            ],
            options={
                'verbose_name': 'estado',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nome da cidade')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findCity.state', verbose_name='estado')),
            ],
        ),
    ]
